#!/bin/sh
# modded vimpager for nfo files
# colorscheme is at http://github.com/trapd00r/neverland-vim-theme


file="$@"
if [ -z "$file" ]; then file="-"; fi

less_vim() {
    vim -R \
    -c 'let no_plugin_maps = 1' \
    -c 'set scrolloff=999' \
    -c 'runtime! macros/less.vim' \
    -c 'set foldlevel=999' \
    -c 'set nonumber' \
    -c ':colorscheme neverland2' \
    -c 'set laststatus=2' \
    -c 'set textwidth=80' \
    -c 'set cursorline' \
    -c 'set ft=config' \
    "$@"
}

less_vim "$file"
