#!/usr/bin/perl
# abstract: you can't trust $PWD in linux
use strict;
use warnings FATAL => 'all';
use open qw(:std :utf8);
use utf8;
use Cwd qw(getcwd);
my $cwd = getcwd();
print map { -e "$cwd/$_" ? "$cwd/$_\n" : "$_\n" } @ARGV;
