#!/usr/bin/perl
# absname
# you can't trust $PWD in linux
use encoding 'utf8';
use open qw(:std :utf8);
use utf8;
use Cwd qw(getcwd);
$\="\n";
print map { my $cwd = getcwd(); -e "$cwd/$_" ? "$cwd/$_\n" : "$_\n" } @ARGV;
