#!/bin/sh
# abstract: display all albums by artist

artist="$@"
[ -z $artist ] && artist=$(mpc --format '%artist%' | head -1)
mpc search artist "$artist" \
  | perl -pe 's{(.+)/.+$}{$1}' \
  | sort -u \
  | perl -pe "s!^!\$ENV{XDG_MUSIC_DIR}!e"
