#!/usr/bin/perl
use strict;
use vars qw($VERSION);
my $APP  = 'aur3c';
$VERSION = '0.001';

use Data::Dumper;

{
  package Data::Dumper;
  no strict 'vars';
  $Terse = $Indent = $Useqq = $Deparse = $Sortkeys = 1;
  $Quotekeys = 0;
}

# http://aur.archlinux.org/rpc.php?type=info&arg=jshon
# http://aur3.org/rpc/$pkg

use LWP::Simple;

my $pkg = shift // 'pimpd2-git';
my $base = "http://aur3.org/rpc/$pkg";

my %pkg;
for(split(/\n/, get($base))) {
  if($_ =~ m/"(.+)": (.+),/) {
    my($t, $v) = ($1, $2);
    $v =~ s/"//g;
    $pkg{$t} = $v;
  }
}

for(qw(name description votes pkgsite submitted lastupdate)) {
  printf("%15s: %s\n", $_, $pkg{$_}) unless(!exists($pkg{$_}));
}




__END__


=pod

=head1 NAME

aur3c - aur3 client

=head1 USAGE

  aur3c <pkg>

=head1 REPORTING BUGS

Report bugs and/or feature requests on rt.cpan.org, the repository issue tracker
or directly to L<magnus@trapd00r.se>

=head1 AUTHOR

  Magnus Woldrich
  CPAN ID: WOLDRICH
  magnus@trapd00r.se
  http://japh.se

=head1 CONTRIBUTORS

None required yet.

=head1 COPYRIGHT

Copyright 2011 B<THIS APPLICATION>s L</AUTHOR> and L</CONTRIBUTORS> as listed
above.

=head1 LICENSE

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=head1 SEE ALSO

=cut

# vim: set ts=2 et sw=2:

