#!/usr/bin/perl
# vim:ft=perl:et:
# abstract: grab input from stdin and basename it

use strict;
use File::Basename;
use File::LsColor qw(ls_color);


my $colored = $ARGV[0] =~ m/--?c/;
shift @ARGV if $colored;

while(<>) {
  chomp;
  my $file = basename($_);
  printf "%s\n", $colored ? ls_color($file) : $file;
}
