#!/bin/zsh
# vim:ft=zsh:
# abstract: importing single tracks and placing them where they belong
# -> Artist/+tracks/

printf "importing \033[38;5;197;3;1mSINGLE\033[m tracks\n"
printf "placing them in +tracks/\n"

printf "\033[38;5;220;1martist\033[m: "
read  ARTIST

printf "> running beet import -Sa --set artist='$ARTIST' *(.) OK?\n"

read foo

# -s singleton mode
# -A noautotag
beet import -sA --set artist="$ARTIST" *(.) "$@"
