#!/bin/zsh
# vim:ft=zsh:
# abstract: importing single tracks and placing them where they belong
# -> Artist/+tracks/

# -- new version

# first, run vidir and clean up the filenames to a %artist - %title
# template

# clear all tags
id3shit -s *(.)

# read artist and title from filename after a vidir cleanup
lltag --yes -F '%a - %t' *(.)

# import to beets
#   -s singleton mode
#   -A noautotag
#   -W no write
; beet import -sAW *(.) "$@"
