#!/bin/sh
# abstract: mount bob the boxeebox

mkdir -p /mnt/bob
mount -t cifs //BOXEEBOX/bob /mnt/bob \
  -o user=guest            \
  -o password=a            \
  -o uid=scp1              \
  -o gid=users             \
  -o workgroup=workgroup   \
  -o ip=192.168.10.158     \
  -o iocharset=utf8        \
  -o vers=1.0
