#!/usr/bin/perl
# abstract: bold input

use strict;
use Term::ExtendedColor qw(:attributes);

if(!(@ARGV)) {
  while(<>) {
    chomp;
    printf "%s\n", bold($_);
  }
}
else {
  printf "%s\n", bold("@ARGV");
}
