#!/usr/bin/perl
use strict;
# calc

print "Expression?\n";
while (1) {
  print '> ';
  chomp(my $cmd = <STDIN>);
  exit if ($cmd =~ /^\s*:q\s*/);
  my $i = eval $cmd;
  printf("%d 0x%x 0%o %b %f %s \n", $i, $i, $i, $i, $i, $i);
}

