#!/bin/zsh
# vim: ft=sh smc=78 cc=:
setopt extendedglob nullglob nomatch
=rm -vr (#i)**/{sample,subs,proof}(/)
=rm -vi (#i)**/*.{rar,r[0-9][0-9],sfv,nfo,ion,ini,txt,url,htm*,exe,pdf,bak,*_Store,lnk}(.)
