#!/usr/bin/perl
# colorscheme.pl
# The colorscheme I've been using for ~2 years

use strict;
use Term::ExtendedColor::Xresources qw(set_xterm_color);


my %colors = (
  0  => '121212',
  8  => 'ffffff',
  1  => 'ff4747',
  9  => 'ff6767',
  2  => '2b4626',
  10 => 'b03b31',
  3  => 'ff8f00',
  11 => 'bdf13d',
  4  => '1165e9',
  12 => '5496ff',
  5  => 'aef7a4',
  13 => 'b50077',
  6  => 'cb1c13',
  14 => '6be603',
  7  => 'fcdeaf',
  15 => 'abcdef',
);


for my $ansi(keys(%colors)) {
  print values %{ set_xterm_color({$ansi => $colors{$ansi} }) };
}
