#!/bin/sh
# abstract: cpan regular releasers

curl -s --user-agent p5p http://neilb.org/cpan-regulars/ \
  | html2txt \
  | tail -12 \
  | perl -pe 's/WOLDRICH/\033[48;5;196;1;38;5;225mWOLDRICH\033[m/'
