#!/usr/bin/perl
use strict;

use JSON::XS;
use LWP::Simple;
use Data::Dumper;

{
  package Data::Dumper;
  no strict "vars";

  $Terse = $Indent = $Useqq = $Deparse = $Sortkeys = 1;
  $Quotekeys = 0;
}


#http://api.metacpan.org/dist/_search\?q\=name:colorcoke

my $author = shift // 'woldrich';
my $url_author = 'http://api.metacpan.org/module/_search?q=author:';

my $str = decode_json( get("$url_author/$author") );

print Dumper $str;
