#!/bin/sh
curl -s -XPOST api.beta.metacpan.org/release/_search -d '{
  "query": {
    "match_all": {}
  },
  "size": 999999,
  "filter": {
    "term": {
      "release.dependency.module": "Term::ExtendedColor"
    }
  }
}' | json_deparse
