#!/bin/bash
# transfer the playing song on the remote mpd server to the local box

target=$HOME/http/japh.se/music

if [ -d $target ]; then
  file="/mnt/Music_1/$(mpc -h $MPD_HOST --format '%file%'|head -1)"
  file=$(echo $file| perl -pe 's/([;<>\*\|&\$!#\(\)\[\]\{\}:])/\\$1/gm');
  scp -P 19217 scp1@192.168.1.128:"'$file'" $target
fi
