" define :commands for each of the available colorschemes:
"   :neverland
"   :github
"   :desert

"exe 'command ' . substitute(cs, '\v[^a-zA-Z0-9_]', '_', 'g')  . ' colorscheme ' . cs

" really weird stuff happened, it might be because I was doing
"   exe 'color ' . cs 
" here ':color' not being enough. investigate
silent! delcommand colorbuffer
silent! delcommand colordefault

" doing ctermfg=bg ctermbg=fg doesn't work - E420
let [new_fg, new_bg] = (&t_Co > 255)
    \ ? (&background == 'dark') ? [225, 232] : [232, 218]
    \ : (&background == 'dark') ? [7, 0]     : [0, 7]

for cs in map(
\  split(globpath(expand("$VIMRUNTIME"), "/colors/*.vim"), "\n"), 'fnamemodify(v:val, ":t:r")' 
\)
  exe printf(
    \ 'hi! clear | colorscheme %s | %s | %s | %s | %s | %s | %s | %s | %s | %s',
    \ cs,
    \ 'hi Normal         ctermfg=' . new_fg . 'ctermbg=' . new_bg ,
    \ 'hi ColorColumn    ctermfg=221 ctermbg=234 cterm=none       ',
    \ 'hi CursorColumn   ctermfg=233 ctermbg=124 cterm=boldreverse',
    \ 'hi CursorLine     ctermfg=000 ctermbg=250 cterm=reverse    ',
    \ 'hi LineNr         ctermfg=231 ctermbg=244 cterm=reverse   ',
    \ 'hi CursorLineNr   ctermfg=196 ctermbg=233 cterm=reverse  ',
    \ 'hi FoldColumn     ctermfg=067 ctermbg=232',
    \ 'redraw | colorscheme | hi Normal',
    \ 'sleep 900m',
  \)
endfor

"256_adaryn.vim
"256_asu1dark.vim
"256_automation.vim
"256_blackdust.vim
"256_darkdot.vim
"256-grayvim.vim
"256-jungle.vim
"256_redblack.vim
"3dglasses.vim
"adam.vim
"adaryn.vim
"adobe.vim
"adrian.vim
"advantage.vim
"af.vim
"aiseered.vim
"alexmax.vim
"anotherdark.vim
"ansi_blows.vim
"aqua.vim
"ashen.vim
"asmanian_blood.vim
"asu1dark.vim
"automation.vim
"autumnleaf.vim
"autumn.vim
"basic.vim
"baycomb.vim
"bayQua.vim
"bclear.vim
"beachcomber.vim
"beauty256.vim
"bensday.vim
"billw.vim
"biogoo.vim
"black_angus.vim
"blackbeauty.vim
"blackboard.vim
"blackdust.vim
"blacklight.vim
"BlackSea.vim
"blazer.vim
"blink.vim
"bluechia.vim
"bluegreen.vim
"blueprint.vim
"blueshift.vim
"blue.vim
"bluez.vim
"blugrine.vim
"bmichaelsen.vim
"bocau.vim
"bog.vim
"borland.vim
"brookstream.vim
"brown.vim
"busierbee.vim
"busybee.vim
"BusyBee.vim
"buttercream.vim
"bvemu.vim
"bw.vim
"calmar256-light.vim
"camo.vim
"campfire.vim
"candycode.vim
"candyman.vim
"candy.vim
"caramel.vim
"carrot.vim
"carvedwoodcool.vim
"carvedwood.vim
"chance-of-storm.vim
"charged-256.vim
"charon.vim
"chela_light.vim
"chlordane.vim
"ChocolateLiquor.vim
"ChocolatePapaya.vim
"chocolate.vim
"chris2.vim
"chrysoprase.vim
"ciscoacl.vim
"clarity.vim
"cleanphp.vim
"cloudy.vim
"clue.vim
"cobaltish.vim
"cobalt.vim
"codeblocks_dark.vim
"codeburn.vim
"CodeFactoryv3.vim
"coffee.vim
"coldgreen.vim
"colorer.vim
"colorful256.vim
"colorful.vim
"colorscheme_template.vim
"colorzone.vim
"contrasty.vim
"cool.vim
"corn.vim
"corporation.vim
"cthulhian.vim
"custom.vim
"c.vim
"d8g_01.vim
"d8g_02.vim
"d8g_03.vim
"d8g_04.vim
"dante.vim
"darkblack.vim
"darkblue2.vim
"darkblue.vim
"darkBlue.vim
"darkbone.vim
"darkburn.vim
"darkdot2.vim
"darkdot.vim
"darkeclipse.vim
"darkerdesert.vim
"darker-robin.vim
"darkocean.vim
"darkrobot.vim
"darkroom.vim
"dark-ruby.vim
"darkslategray.vim
"darkspectrum.vim
"darktango.vim
"darkzen.vim
"darkZ.vim
"dawn.vim
"default.vim
"delek.vim
"delphi.vim
"denim.vim
"derefined.vim
"desert256.vim
"desertedoceanburnt.vim
"desertedocean.vim
"desertEx.vim
"desert.vim
"devbox-dark-256.vim
"DevC++.vim
"deveiate.vim
"developer.vim
"devolved.vim
"Digerati_Vim_Colorscheme_by_hcalves.vim
"django.vim
"donbass.vim
"doorhinge.vim
"doriath.vim
"dual.vim
"dull.vim
"dusk.vim
"earendel.vim
"earthburn.vim
"earth.vim
"eclipse.vim
"eclm_wombat.vim
"edo_sea.vim
"ego.vim
"ekinivim.vim
"ekvoli.vim
"elflord.vim
"elise.vim
"elisex.vim
"emacs.vim
"enzyme.vim
"evening_2.vim
"evening.vim
"far.vim
"fine_blue.vim
"fnaqevan.vim
"fog.vim
"fokus.vim
"forneus.vim
"freya.vim
"fruidle.vim
"fruit.vim
"fruity.vim
"fu.vim
"gardener.vim
"gemcolors.vim
"gentooish.vim
"getafe.vim
"github.vim
"gnum.vim
"gobo.vim
"golded.vim
"golden.vim
"google.vim
"gor.vim
"gothic.vim
"grape.vim
"graywh.vim
"greens.vim
"greenvision.vim
"grey2.vim
"greyblue.vim
"guardian.vim
"guepardo.vim
"h80.vim
"habiLight.vim
"heliotrope.vim
"herald.vim
"/home/scp1/dev/vim/runtime/colors:
"/home/scp1/etc/vim/colors:
"hornet.vim
"ibmedit.vim
"icansee.vim
"impactG.vim
"impact.vim
"industrial.vim
"ingretu.vim
"inkpot.vim
"ir_black.vim
"ironman.vim
"jammy.vim
"jelleybeans.vim
"jellybeans.vim
"jellyx.vim
"jhdark.vim
"jhlight.vim
"kaltex.vim
"kalt.vim
"kate.vim
"kellys.vim
"khaki.vim
"kib_darktango.vim
"kib_plastic.vim
"kiss.vim
"kkruby.vim
"koehler.vim
"kruby.vim
"lazarus.vim
"legiblelight.vim
"leglight2.vim
"leo.vim
"less.vim
"lettuce.vim
"lightcolors.vim
"lilac.vim
"lilydjwg_dark.vim
"lilydjwg_green.vim
"lilypink.vim
"lingodirector.vim
"liquidcarbon.vim
"literal_tango.vim
"lodestone.vim
"louver.vim
"lucius.vim
"luinnar.vim
"manuscript.vim
"manxome.vim
"marklar.vim
"maroloccio.vim
"mars.vim
"martin_krischik.vim
"matrix.vim
"mayansmoke.vim
"mdark.vim
"mellow.vim
"metacosm.vim
"midnight2.vim
"midnight.vim
"miko.vim
"mint.vim
"mizore.vim
"mod_tcsoft.vim
"molokai.vim
"montz.vim
"mophiaDark.vim
"mophiaSmoke.vim
"moria.vim
"morning.vim
"moss.vim
"motus.vim
"MountainDew.vim
"mrkn256.vim
"mrpink.vim
"mud.vim
"murphy.vim
"mustang.vim
"Mustang_Vim_Colorscheme_by_hcalves.vim
"native.vim
"nature.vim
"navajo-night.vim
"navajo.vim
"nazca.vim
"nedit2.vim
"nedit.vim
"neutron.vim
"neverland-ansi_bg-shiva.vim
"neverland-ansi_bg.vim
"neverland-ansi-two.vim
"neverland-ansi.vim
"neverland-darker-shiva.vim
"neverland-darker.vim
"neverland-monochrome.vim
"neverness.vim
"nevfn.vim
"newspaper.vim
"newsprint.vim
"nicotine.vim
"nightflight2.vim
"nightflight.vim
"nightshimmer.vim
"nightsky.vim
"night.vim
"night_vision.vim
"nightVision.vim
"nightwish.vim
"no_quarter.vim
"northland.vim
"northsky.vim
"norwaytoday.vim
"nour.vim
"nuvola.vim
"ö
"obsidian2.vim
"obsidian.vim
"oceanblack256.vim
"oceanblack.vim
"oceandeep.vim
"oceanlight.vim
"olive.vim
"orange.vim
"org_dark.vim
"osx_like.vim
"pablo.vim
"pacific.vim
"paintbox.vim
"PapayaWhip.vim
"peachpuff.vim
"peaksea.vim
"peppers.vim
"perfect.vim
"pf_earth.vim
"phd.vim
"phphaxor.vim
"phpx.vim
"pic.vim
"pink.vim
"pleasant.vim
"potts.vim
"print_bw.vim
"prmths.vim
"professional.vim
"proton.vim
"pspad.vim
"psql.vim
"putty.vim
"pw.vim
"pyte.vim
"python.vim
"quagmire.vim
"railscasts.vim
"rainbow_fine_blue.vim
"rainbow_fruit.vim
"random.vim
"rastafari.vim
"rcg_gui.vim
"rcg_term.vim
"rdark-terminal.vim
"rdark.vim
"README.txt
"redblack.vim
"redstring.vim
"refactor.vim
"relaxedgreen.vim
"reliable.vim
"reloaded.vim
"revolutions.vim
"robinhood.vim
"ron.vim
"rootwater.vim
"rtl.vim
"sand.vim
"satori.vim
"scala.vim
"scite.vim
"sean.vim
"seashell.vim
"selenitic.vim
"seoul.vim
"settlemyer.vim
"sf.vim
"shadesofamber.vim
"shine.vim
"shobogenzo.vim
"sienna.vim
"sift.vim
"silent.vim
"simple256.vim
"simpleandfriendly.vim
"simple_b.vim
"simplewhite.vim
"skittles_dark.vim
"slate.vim
"smp.vim
"softbluev2.vim
"softblue.vim
"softlight.vim
"sonofobsidian.vim
"sorcerer.vim
"soso.vim
"southernlights.vim
"southwest-fog.vim
"spectro.vim
"spiderhawk.vim
"spring.vim
"stackoverflow.vim
"stingray.vim
"strawimodo.vim
"summerfruit256.vim
"summerfruit.vim
"surveyor.vim
"symfony.vim
"synic.vim
"tabula.vim
"tango2.vim
"tango-desert.vim
"tango-morning.vim
"tangoshady.vim
"tango.vim
"taqua.vim
"tchaba.vim
"tcsoft.vim
"telstar.vim
"tesla.vim
"tetragrammaton.vim
"textmate16.vim
"thegoodluck.vim
"thestars.vim
"tibet.vim
"tidy.vim
"tir_black.vim
"toga.vim
"tolerable.vim
"tomatosoup.vim
"tony_light.vim
"toothpik.vim
"torte.vim
"transparent.vim
"trivial256.vim
"trogdor.vim
"turbo.vim
"tutticolori.vim
"twilight256.vim
"twilight.vim
"two2tango.vim
"typing.vim
"umber-green.vim
"understated.vim
"underwater-mod.vim
"underwater.vim
"up.vim
"vanzan_color.vim
"vcbc.vim
"vc.vim
"vexorian.vim
"vibrantink.vim
"vilight.vim
"vitamin.vim
"vividchalk.vim
"vj.vim
"void.vim
"vydark.vim
"vylight.vim
"wargrey.vim
"warm_grey.vim
"watermark.vim
"whitebox.vim
"whitedust.vim
"widower.vim
"win9xblueback.vim
"wintersday.vim
"winter.vim
"wombat256mod.vim
"wombat256.vim
"wombat.vim
"wood.vim
"wuye.vim
"xemacs.vim
"xian.vim
"xmaslights.vim
"xoria256.vim
"yaml.vim
"yeller.vim
"zazen.vim
"zellner.vim
"zenburn.vim
"zenesque.vim
"zen.vim
"zephyr.vim
"zmrok.vim
