#!/usr/bin/perl
# dmenuclip.pl
# REALLY nasty... 
use strict;
my $xsels = "/home/scp1/.config/dmenuclip/xsel";
my $f     = '-*-fixed-*-*-*-*-15-*-*-*-*-*-*-*';
my $dmenu = 'dmenu -i -b -nb \#1c1c1c -nf \#d7005f -sb \#252525';



system("printf \"\$(\\cat $xsels|$dmenu -fn $f -p xsel)\"|xclip -i -l 0|xclip -o");
