#!/usr/bin/perl
# dmenuclip-syncd
# Daemon that collects the X selections and saves them in a plaintext file
# for future use with dmenuclip
# dmenuclip helper scriptfor syncing the X selections
use strict;
use Proc::Daemon;
my $xsel = "$ENV{'HOME'}/.config/dmenuclip/xsel";
#use Data::Dumper;

sub syncIt {
  print "Daemonizing...\n";
  Proc::Daemon::Init;
  while(1) {
    open(XSEL,"<", $xsel) or die "Cant open $xsel for reading: $!";
    my @lines = <XSEL>;
    chomp @lines;
    close XSEL;
    my $currentSel = `/usr/bin/xclip -o`;
    chomp($currentSel);
    #print Dumper($currentSel);
    if($currentSel ~~ @lines) {
      &syncSec(0);
    }
    else {
      open(XSEL_W, ">>", $xsel) or die "Cant open $xsel for writing: $!";
      print XSEL_W "$currentSel\n";
      close XSEL_W;
    }
    sleep 2;
  }
}

&syncIt;

# Those are deprecated, but left here for reference
sub syncPrim {
  system("/usr/bin/xclip -o --selection primary -o) >> $xsel&&printf \"\n\" >> $xsel");
}
sub syncSec {
  my $c = shift;
  unless($c == 0) {
    system("/usr/bin/xclip -o >> $xsel"); #&& printf \"\n\" >> $xsel");
  }
}
