#!/usr/bin/perl
use strict;

#open(my $fh, '<', '/usr/share/dict/cracklib-small') or die($!);
open(my $fh, '<', "$ENV{HOME}/usr/share/doc/wordlists/big.txt");
my @words = grep{ (length($_) > 4) && lc(chomp($_)) } (<$fh>);

my $tld =  (shift // 'se');


my $limit = shift // 25;
my $count = 0;
for my $w( sort{ length($a) <=> length($b) } grep{ m/$tld/ } @words) {
  if($count == $limit) {
    exit;
  }
  if($w =~ s{$tld$}{.$tld}) {
    if(_not_registred( $w )) {
      print "$w\n";
      $count++;
    }
  }
}

sub _not_registred {
  my $d = shift;
  open(my $fh, '-|', "whois $d") or die($!);
  while(<$fh>) {
    if($_ =~ m/not found[.]$/) {
      return 1;
    }
  }
  return;
}
