#!/usr/bin/perl
use strict;

#open(my $fh, '<', '/usr/share/dict/cracklib-small') or die($!);
open(my $fh, '<', '/tmp/scp1/svenska.txt') or die($!);
my @words = grep{ (length($_) > 4) && lc(chomp($_)) } (<$fh>);

my $tld =  (shift // 'se');

for my $w( sort{ length($a) <=> length($b) } grep{ m/$tld/ } @words) {
  if($w =~ s{$tld$}{.$tld}) {
    if(_not_registred( $w )) {
      print "$w\n";
    }
  }
}

sub _not_registred {
  my $d = shift;
  open(my $fh, '-|', "whois $d") or die($!);
  while(<$fh>) {
    if($_ =~ m/not found[.]$/) {
      return 1;
    }
  }
  return;
}
