#!/bin/sh
# vim: ft=sh et sw=2 smc=80 cc=:

where="${@:-.}"
printf '\033[?7l'

# hi, I was going to explain why the abuse of the %d format specifier for the
# first column is not a bug, but there's pie in the kitchen that needs to be
# eaten and you, you could need some exercise
dush  -mfdcsn $(($(stty size|awk '{print $1}') / 2)) $where 2>&1 \
  | awk -F: '
  {
    printf("\033[38;5;202;1m% 6d\033[m\033[38;5;241mMB\033[m \033[38;5;86m%1s\033[m\033[38;5;30m%s\033[m\n", $2, "", $1 )
  }
'
printf '\033[?7h'
