#!/bin/sh
# vim: ft=zsh et sw=2:

# FIXME - stty hack
LINES=90
dush  -mfdcsn $(($LINES/4)) "$@" 2>&1 \
  | awk '
  {
    gsub(/:$/, "", $1);
    printf("% 6d \033[1m% 1s\033[m \033[1m%s\033[m\n", $2, $3, $1 )
  }
'
