#!/usr/bin/perl
use strict;

my $time = @ARGV ? shift : <>;
my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime($time);

my %days = (
  0 => 'Sunday',
  1 => 'Monday',
  2 => 'Tuesday',
  3 => 'Wednesday',
  4 => 'Thursday',
  5 => 'Friday',
  6 => 'Saturday',
  7 => 'Sunday',
);

printf "%s %s-%02d-%02d %02d:%02d:%02d\n", $days{$wday}, $year += 1900, $mon += 1, $mday, $hour, $min, $sec,
