#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';

my $command = shift;

open(my $fh, '<', "$ENV{HOME}/.ssh/config") or die $!;
my @hosts;
while(my $l = <$fh>) {
  next if $l =~ /^#/;
  if ($l =~ m/^[Hh]ost\s+([\w.]+)/ and $1 ne $ENV{HOSTNAME}) {
    push(@hosts, $1);
  }
}

#close(STDERR) or die "cant close STDERR: $!\n";
for my $h(sort(@hosts)) {
  print STDERR sprintf "%-10s ", $h;
  system('ssh', $h, $command);
}
print STDERR sprintf "%-10s ", $ENV{HOSTNAME};
system($command);

END {
#  open(STDERR, '>', '/dev/fd/2') or die "Cant reopen STDERR: $!\n";
}
