#!/usr/bin/perl
# abstract: how many times have $url been shared on facebook?

use LWP::Simple;

my $url = shift || 'http://graph.facebook.com/'; # 75 2011-03-21
$url = "http://$url" if $url !~ /^http/;

print get( "http://graph.facebook.com/$url" );
