#!/usr/bin/perl

use strict;
use warnings FATAL => 'all';

open(my $popen, '-|', "/usr/bin/fc-list @ARGV") or die $!;

my @fonts = sort(map { chomp; "'xft:$_:antialias=1:hinting=1'" } <$popen>);

print "$_\n" for @fonts;
