#!/usr/bin/perl

use strict;
use warnings FATAL => 'all';

my $pz = shift || 10;

open(my $popen, '-|', "/usr/bin/fc-list @ARGV") or die $!;

my @fonts = sort(map { chomp; "'xft:$_:pixelsize=$pz:antialias=1:hinting=1:hintstyle=3'" } <$popen>);

print "$_\n" for @fonts;
