#!/usr/bin/perl
# vim: ft=perl:fdm=marker:fmr=#<,#>:fen:et:sw=2:
use strict;
use warnings FATAL => 'all';
use vars     qw($VERSION);
use autodie  qw(:all);

use utf8;
use open qw(:std :utf8);

my $APP  = '';
$VERSION = '0.001';

use Data::Dumper;

{
  package Data::Dumper;
  no strict 'vars';
  $Terse = $Indent = $Useqq = $Deparse = $Sortkeys = 1;
  $Quotekeys = 0;
}

use MP3::Info;
use File::LsColor qw(ls_color);
use Term::ExtendedColor qw(fg bg);

die "No files specified!\n" unless grep { -f $_ } @ARGV;
my @files = grep { m/[.]mp3$/ } @ARGV;


for my $file(@files) {
  my $tag = get_mp3tag($file);

  if(! defined($tag)) {
DO_IT_ANYWAY:
    my($artist, $title) = $file  =~ m/(.+)\s+-\s+(.+)[.]mp3/;

    printf "artist: $artist\ntitle: $title\n";
    set_mp3tag($file,
    {
     ARTIST => $artist,
     TITLE  => $title,
    });
  }
  else {
    printf "%s\n", bg(160, 'TAG EXISTS!');
    printf "%s\n artist: %s\n  title: %s\n",
      ls_color($file), $tag->{ARTIST}, $tag->{TITLE};
  }
}


=begin comment


Here goes inline comments that won't show up in pod doc

=end comment


=cut




__END__


=pod

=head1 NAME

=head1 USAGE

=head1 DESCRIPTION

=head1 OPTIONS

=head1 REPORTING BUGS

Report bugs and/or feature requests on rt.cpan.org, the repository issue tracker
or directly to L<m@japh.se>

=head1 AUTHOR

  Magnus Woldrich
  CPAN ID: WOLDRICH
  m@japh.se
  L<~/|http://japh.se>
  L<git|http://github.com/trapd00r>

=head1 CONTRIBUTORS

None required yet.

=head1 COPYRIGHT

Copyright 2019- B<THIS APPLICATION>s L</AUTHOR> and L</CONTRIBUTORS> as listed
above.

=head1 LICENSE

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=head1 SEE ALSO

L<~/|http://japh.se>

=cut

