#!/bin/sh
umount /mnt/mp3
mount /dev/sdi1 /mnt/mp3   && \
  cd /mnt/mp3/MUSIC        && \
  rmfile *                 && \
  mv /home/scp1/toburn/* . && \
  cd /mnt                  && \
  umount mp3               && \
  printf '\e[38;5;34;1mFinished.\e[m\n'
