#!/usr/bin/perl
# vim:ft=perl:
use strict;
# abstract: use fifos to control mpd using mpc

sub readFifo {
  my $FIFO = shift;
  while(1) {
    unless(-p $FIFO) {
      unlink $FIFO;
      system('mknod', $FIFO, 'p');
    }
    open(FIFOR, "< $FIFO") or die "Cannot read $FIFO: $!\n";
    while(<FIFOR>) {
      my $cmd = $_;
      system("mpc $cmd");
    }
  }
}

&readFifo('/tmp/tompc');
