#!/bin/sh

printf '\e]710;%s\a' \
  'xft:Fixed:weight=light:pixelsize=10:antialias=0'
printf '\e]711;%s\a' \
  'xft:Fixed:weight=bold:pixelsize=10:antialias=0'
printf '\e]712;%s\a' \
  'xft:Fixed:pixelsize=9:antialias=0'
