#!/bin/sh

printf '\033]710;%s\007' \
  'xft:monofur:style=Regular:pixelsize=16:antialias=1:hinting=1'
printf '\033]711;%s\007' \
  'xft:monofur:pixelsize=16:antialias=1:hinting=1:embolden=1'
printf '\033]712;%s\007' \
  'xft:monofur:pixelsize=16:antialias=1:hinting=1:slant=italic'
printf '\033]713;%s\007' \
  '-xos4-terminus-medium-r-normal--16-160-72-72-c-80-koi8-u'
