#!/bin/sh

printf '\033]710;%s\007' \
  'xft:DejaVu Sans Mono:style=Book:pixelsize=13:antialias=1:hinting=1:hintstyle=3'
printf '\033]711;%s\007' \
  'xft:DejaVu Sans Mono:style=Bold:pixelsize=13:antialias=1:hinting=1:hintstyle=3'
printf '\033]712;%s\007' \
  'xft:DejaVu LGC Sans Mono:style=Book:pixelsize=13:antialias=1:hinting=1:hintstyle=3:embolden=1'
printf '\033]713;%s\007' \
  'xft:DejaVu Sans Mono:style=Book:pixelsize=13:antialias=1:hinting=1:hintstyle=3'
