#!/bin/sh

printf '\e]710;%s\a' \
  'xft:Droid Sans Mono Slashed:style=Regular:pixelsize=24:antialias=1:hinting=1'
printf '\e]711;%s\a' \
  'xft:Droid Sans Mono Slashed:pixelsize=24:antialias=1:hinting=1:embolden=1'
printf '\e]712;%s\a' \
  'xft:Droid Sans Mono Slashed:pixelsize=24:antialias=1:hinting=1:slant=italic'
printf '\e]713;%s\a' \
  -xos4-terminus-bold-r-normal--24-240-72-72-c-120-koi8-u
