#!/bin/sh

printf '\e]710;%s\a' \
  'xft:Anonymous Pro:style=Regular:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
printf '\e]711;%s\a' \
  'xft:Anonymous Pro:style=Bold:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
printf '\e]712;%s\a' \
  'xft:Anonymous Pro:style=Italic:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
printf '\e]713;%s\a' \
  'xft:Anonymous Pro:style=Bold Italic:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
