#!/bin/sh
printf '\033]710;%s\007' \
  'xft:ProFontWindows Nerd Font Mono:style=Book:pixelsize=12:antialias=0:hinting=none:hintstyle=0'
printf '\033]711;%s\007' \
  'xft:ProFont:style=Regular:pixelsize=10:embolden=1'
printf '\033]712;%s\007' \
  'xft:ProFontIIx Nerd Font Mono:style=Book:pixelsize=9:antialias=0:hinting=0:hintstyle=0'
printf '\033]713;%s\007' \
  '-windows-montecarlo-bold-r-normal--11-110-72-72-c-60-microsoft-cp1252'
