#!/bin/sh

printf '\033]710;%s\007' \
  'xft:Anonymous Pro:style=Regular:pixelsize=12:antialias=1:hinting=1:hintstyle=3'
printf '\033]711;%s\007' \
  'xft:Anonymous Pro:style=Bold:pixelsize=12:antialias=1:hinting=1:hintstyle=3'
printf '\033]712;%s\007' \
  'xft:Anonymous Pro:style=Italic:pixelsize=12:antialias=1:hinting=1:hintstyle=3'
printf '\033]713;%s\007' \
  'xft:Anonymous Pro:style=Bold Italic:pixelsize=12:antialias=1:hinting=1:hintstyle=3'
