#!/bin/sh
printf '\e]710;%s\a' \
  -windows-montecarlo-medium-r-normal--11-110-72-72-c-60-microsoft-cp1252
printf '\e]711;%s\a' \
  -windows-montecarlo-bold-r-normal--11-110-72-72-c-60-microsoft-cp1252
printf '\e]712;%s\a' \
  -nil-profont-medium-r-normal--10-100-72-72-c-50-iso8859-1
