#!/bin/sh

printf '\033]710;%s\007' \
  'xft:UbuntuTitleBook:style=Book,Ubuntu-Title'

printf '\033]711;%s\007' \
  'xft:UbuntuTitleBold:style=Bold,Ubuntu-Title:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
printf '\033]712;%s\007' \
'xft:Liberation Sans Narrow:style=Regular:pixelsize=10:antialias=1:hinting=1:hintstyle=3'



#  'xft:Ubuntu,Ubuntu Light:style=Light Italic,Italic:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
#  'xft:DejaVu LGC Sans Mono:style=Book:pixelsize=10:antialias=1:hinting=1:hintstyle=3:embolden=1'
printf '\033]713;%s\007' \
  'xft:DejaVu Sans Mono:style=Book:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
#  'xft:Ubuntu:style=Bold Italic:pixelsize=10:antialias=1:hinting=1:hintstyle=4'
