#!/bin/sh

printf '\033]710;%s\a' \
  'xft:Anonymous Pro:style=Regular:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
printf '\033]711;%s\a' \
    "xft:Anonymous Pro:style=Bold:pixelsize=10:antialias=0:hinting=0:hintstyle=3"
printf '\033]712;%s\a' \
  '-misc-fixed-medium-r-normal--10-100-75-75-c-60-iso8859-1'
printf '\033]713;%s\a' \
  'neep-10'
