#!/bin/sh

printf '\033]710;%s\007' \
  'xft:ProggyTinyTTSZ:weight=light:spacing=proportional:pixelsize=15:antialias=0:hinting=0:width=condensed'
printf '\033]711;%s\007' \
  'xft:Fixed:pixelsize=10:antialias=0:weight=light'
printf '\033]712;%s\007' \
  'xft:Fixed:pixelsize=9:antialias=0'
