#!/bin/sh

printf '\033]710;%s\007' \
  'xft:Fixed:weight=light:pixelsize=10:antialias=0'
printf '\033]711;%s\007' \
  'xft:Fixed:weight=bold:pixelsize=10:antialias=0'
printf '\033]712;%s\007' \
  'xft:Fixed:pixelsize=9:antialias=0'
printf '\033]713;%s\007' \
  'xft:DejaVu Sans Mono:style=Book:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
