#!/bin/sh

printf '\033]710;%s\007' \
  'xft:Droid Sans Mono Slashed:style=Regular:pixelsize=16:antialias=1:hinting=1'
printf '\033]711;%s\007' \
  'xft:Droid Sans Mono Slashed:pixelsize=16:antialias=1:hinting=1:embolden=1'
printf '\033]712;%s\007' \
  'xft:Droid Sans Mono Slashed:pixelsize=16:antialias=1:hinting=1:slant=italic'
printf '\033]713;%s\007' \
  '-nil-profont-medium-r-normal--15-150-72-72-c-70-iso8859-1'
