#!/bin/sh

printf '\e]710;%s\a' \
  'xft:UbuntuTitleBook:style=Book,Ubuntu-Title'

printf '\e]711;%s\a' \
  'xft:UbuntuTitleBold:style=Bold,Ubuntu-Title:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
printf '\e]712;%s\a' \
'xft:Liberation Sans Narrow:style=Regular:pixelsize=10:antialias=1:hinting=1:hintstyle=3'



#  'xft:Ubuntu,Ubuntu Light:style=Light Italic,Italic:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
#  'xft:DejaVu LGC Sans Mono:style=Book:pixelsize=10:antialias=1:hinting=1:hintstyle=3:embolden=1'
printf '\e]713;%s\a' \
  'xft:DejaVu Sans Mono:style=Book:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
#  'xft:Ubuntu:style=Bold Italic:pixelsize=10:antialias=1:hinting=1:hintstyle=4'
