#!/bin/sh
printf '\033]710;%s\007' 5x7
printf '\033]711;%s\007' 'xft:fixed:pixelsize=7:antialias=1:hinting=1:embolden=1'
printf '\033]712;%s\007' '-schumacher-clean-medium-r-normal--6-60-75-75-c-40-iso646.1991-irv'
printf '\033]713;%s\007' 5x7
