#!/bin/sh

printf '\e]710;%s\a' \
  'xft:Terminus:style=Regular:pixelsize=32:antialias=1:hinting=1'
printf '\e]711;%s\a' \
  'xft:Terminus:style=Bold:pixelsize=32:antialias=1:hinting=1'
printf '\e]712;%s\a' \
  'xft:Aerial Mono:style=italic:pixelsize=32:antialias=1:hinting=1'
printf '\e]713;%s\a' \
  'xft:Aerial Mono:style=Bold Italic:pixelsize=32:antialias=1:hinting=1'
