#!/bin/sh

printf "\033]710;%s\007" 'xft:AnonymicePro Nerd Font:style=Regular:pixelsize=11:antialias=1:hinting=1:hintstyle=3'
printf "\033]711;%s\007" 'xft:AnonymicePro Nerd Font:style=Bold:pixelsize=11:antialias=1:hinting=1:hintstyle=3'
printf "\033]712;%s\007" 'xft:AnonymicePro Nerd Font:style=Italic:pixelsize=11:antialias=1:hinting=1:hintstyle=3'
printf "\033]713;%s\007" 'xft:AnonymicePro Nerd Font:style=Bold Italic:pixelsize=10:antialias=1:hinting=1:hintstyle=3'
