#!/bin/sh
printf "\033]710;%s\007" \
  'xft:Misc Tamsyn:style=Regular:antialias=none:hinting=0:pixelsize=20 '
printf "\033]711;%s\007" \
  'xft:Misc Tamsyn:style=Bold:antialias=none:hinting=0:pixelsize=20 '
printf "\033]712 ;%s\007" \
  'xft:Misc Tamsyn:style=Regular=none:hinting=0:pixelsize=18'
printf "\033]713;%s\007" \
  'xft:Misc Tamsyn:style=Bold:antialias=none:hinting=0:pixelsize=18'
