#!/bin/sh

printf '\e]710;%s\a' \
  'xft:Droid Sans Mono Slashed:style=Regular:pixelsize=12:antialias=1:hinting=1'
printf '\e]711;%s\a' \
  'xft:Droid Sans Mono Slashed:pixelsize=12:antialias=1:hinting=1:embolden=1'
printf '\e]712;%s\a' \
  'xft:Droid Sans Mono Slashed:pixelsize=12:antialias=1:hinting=1:slant=italic'
printf '\e]713;%s\a' \
  '-nil-profont-medium-r-normal--15-150-72-72-c-70-iso8859-1'
