#!/bin/sh
#'xft:C64 Pro Mono:style=Regular:pixelsize=16:antialias=1:hinting=1:hintstyle=3'
#'xft:C64 Pro:style=Regular:pixelsize=16:antialias=1:hinting=1:hintstyle=3'
#'xft:C64 User Mono:style=Regular:pixelsize=16:antialias=1:hinting=1:hintstyle=3'
#'xft:C64 User:style=Regular:pixelsize=16:antialias=1:hinting=1:hintstyle=3'

printf '\e]710;%s\a' \
  'xft:C64 User Mono:style=Regular:pixelsize=16:antialias=1:hinting=1:hintstyle=3'
printf '\e]711;%s\a' \
  'xft:C64 User Mono:style=Regular:embolden=1:pixelsize=16:antialias=1:hinting=1:hintstyle=3'
printf '\e]712;%s\a' \
  'xft:C64 User Mono:style=Regular:slant=italic:pixelsize=16:antialias=1:hinting=1:hintstyle=3'
printf '\e]713;%s\a' \
  'xft:C64 User Mono:style=Regular:embolden=1:slant=italic:pixelsize=16:antialias=1:hinting=1:hintstyle=3'
