#!/bin/sh

printf '\e]710;%s\a' \
  'xft:DejaVu Sans Mono:style=Book:pixelsize=12:antialias=1:hinting=1:hintstyle=3'
printf '\e]711;%s\a' \
  'xft:DejaVu Sans Mono:style=Bold:pixelsize=12:antialias=1:hinting=1:hintstyle=3'
printf '\e]712;%s\a' \
  'xft:DejaVu LGC Sans Mono:style=Book:pixelsize=12:antialias=1:hinting=1:hintstyle=3:embolden=1'
printf '\e]713;%s\a' \
  'xft:DejaVu Sans Mono:style=Book:pixelsize=12:antialias=1:hinting=1:hintstyle=3'
