#!/bin/sh

printf '\e]710;%s\a' \
  'xft:monofur:style=Regular:pixelsize=16:antialias=1:hinting=1'
printf '\e]711;%s\a' \
  'xft:monofur:pixelsize=16:antialias=1:hinting=1:embolden=1'
printf '\e]712;%s\a' \
  'xft:monofur:pixelsize=16:antialias=1:hinting=1:slant=italic'
printf '\e]713;%s\a' \
  '-xos4-terminus-medium-r-normal--16-160-72-72-c-80-koi8-u'
