#!/bin/sh


printf '\e]710;%s\a' \
  "xft:Yoshi's Story game text BRK:style=Regular:pixelsize=20:antialias=1:hinting=1:hintstyle=3"
printf '\e]711;%s\a' \
  "xft:Yoshi's Story game text BRK:style=Bold:pixelsize=20:antialias=1:hinting=1:hintstyle=3"
printf '\e]712;%s\a' \
  "xft:Yoshi's Story game text BRK:style=Italic:pixelsize=20:antialias=1:hinting=1:hintstyle=3"
printf '\e]713;%s\a' \
  "xft:Yoshi's Story game text BRK:style=Black:pixelsize=20:antialias=1:hinting=1:hintstyle=3"
