#!/bin/sh
printf "\033]710;%s\007" 'xft:ProFontIIx Nerd Font Mono:style=Book:pixelsize=9:antialias=0:hinting=0:hintstyle=0'
printf "\033]711;%s\007" 'xft:ProFontIIx Nerd Font Mono:style=Book:pixelsize=9:antialias=1:hinting=1:hintstyle=3'
printf "\033]712;%s\007" 'xft:ProFontIIx Nerd Font Mono:style=Book:pixelsize=9:antialias=1:hinting=1:hintstyle=3'
printf "\033]713;%s\007" 'xft:ProFontIIx Nerd Font Mono:style=Book:pixelsize=9:antialias=1:hinting=1:hintstyle=3'
