#!/bin/sh

printf '\033]710;%s\007' \
  'xft:Droid Sans Mono Slashed:style=Regular:pixelsize=24:antialias=1:hinting=1'
printf '\033]711;%s\007' \
  'xft:Droid Sans Mono Slashed:pixelsize=24:antialias=1:hinting=1:embolden=1'
printf '\033]712;%s\007' \
  'xft:Droid Sans Mono Slashed:pixelsize=24:antialias=1:hinting=1:slant=italic'
printf '\033]713;%s\007' \
  -xos4-terminus-bold-r-normal--24-240-72-72-c-120-koi8-u
