#!/bin/sh

printf '\033]710;%s\007' \
  'xft:Fixed:weight=medium:pixelsize=9:antialias=0'
printf '\033]711;%s\007' \
  'xft:Fixed:weight=bold:pixelsize=9:antialias=0'
printf '\033]712;%s\007' \
  'xft:Fixed:pixelsize=8:antialias=0'
