#!/usr/bin/perl

use strict;
use Term::ExtendedColor;

# Yes, I know
chomp(my @func = `grep -Pi 'sub (.+) \{' \$(find .|grep -Pi '.+(?:pl|pm)\$')`);

my %functions;

for(@func) {
  m;.+/(.+):sub (.+) .+;;
  $functions{$2} = $1;
}

for my $f(sort{ $functions{$a} cmp $functions{$b} }(keys(%functions))) {
  if($f =~ /^_/) {
    printf("%30.30s %s\n",
      fg('yellow18', $functions{$f}),
      fg('blue5', fg('bold', $f)),
    );
  }
  else {
    printf("%30.30s %s\n", fg('green25', $functions{$f}), $f);
  }
}

# vim: set tw=0:
