#!/usr/bin/perl
# vim: ft=perl:fdm=marker:fmr=#<,#>:fen:et:sw=2:
use strict;
use warnings FATAL => 'all';
use vars     qw($VERSION);
use autodie  qw(:all);

use utf8;
use open qw(:std :utf8);

use Power::Outlet::Hue;

my $hue = Power::Outlet::Hue->new(
  host => "192.168.32.2",
  id=>1,
  username => 'W8pQVe4hNRt3jxvWz7oDcSVe0ypOGG-vfONEAlmo',
);


my $command = $hue->query eq 'OFF' ? 'on' : 'off';

$hue->$command;
