#!/usr/bin/perl
use strict;
use feature 'say';
use File::Find::Rule;

my $pattern = shift // '.+';

my @pm = sort(
  File::Find::Rule->file()
                  ->name('*.pm')
                  ->in(@INC)
);

for(@pm) {
  say $_ if $_ =~ m/$pattern/i;
};
