#!/usr/bin/perl
# abstract: italic input

use strict;
use Term::ExtendedColor qw(:attributes);

if(!(@ARGV)) {
  while(<>) {
    chomp;
    printf "%s\n", italic($_);
  }
}
else {
  printf "%s\n", italic("@ARGV");
}
