#!/usr/bin/perl
use strict;

use open qw(:utf8);
use utf8;

use Data::Dumper;
use JSON::XS;

{
  package Data::Dumper;
  no strict "vars";

  $Terse = $Indent = $Useqq = $Deparse = $Sortkeys = 1;
  $Quotekeys = 0;
}

$/ = "";
my $j = <>;
print Dumper decode_json( $j );
