#!/usr/bin/perl
use strict;
use XML::Simple;
use LWP::Simple;
use utf8;
use open qw(:std :utf8);


my $user = shift // 'betbot';
my $url  = "http://ws.audioscrobbler.com/1.0/user/$user/recenttracks.rss";

lfm();

sub lfm {
  my $xml = XML::Simple->new;
  my $content = get($url);

  my $rss = $xml->XMLin($content);

  my $html_title = $rss->{channel}->{item}[0]->{title};

  my($artist, $song) = ('unknown') x 2;
  ($artist, $song) = split(/\x{2013}/, $html_title);

  printf("lastfm: $artist %s\n", ( $song) ? "- $song" : "no record for $user");
}
