#!/usr/bin/perl
use strict;

use Term::ExtendedColor qw(lookup);

my @colors = @ARGV;
if(!@colors) {
  while(<>) {
    chomp;
    push(@colors, $_);
  }
}

print "$_\n" for lookup(\@colors);

__END__

=pod

=head1 NAME

lookup - frontend to  Term::ExtendedColor::lookup

=head1 USAGE

  lookup [INTEGER]

=head1 REPORTING BUGS

Report bugs and/or feature requests on rt.cpan.org, the repository issue tracker
or directly to L<magnus@trapd00r.se>

=head1 AUTHOR

  Magnus Woldrich
  CPAN ID: WOLDRICH
  magnus@trapd00r.se
  http://japh.se

=head1 CONTRIBUTORS

None required yet.

=head1 COPYRIGHT

Copyright 2011 B<THIS APPLICATION>s L</AUTHOR> and L</CONTRIBUTORS> as listed
above.

=head1 LICENSE

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=head1 SEE ALSO

L<Term::ExtendedColor>

=cut

# vim: set ts=2 et sw=2:

