#!/bin/sh
# vim:ft=zsh:
# abstract: love the currently playing song in mpd
# add songs to mpd playlist:
# $ beet ls loved:1
# $ beet2mpd loved:1
# https://github.com/trapd00r/beet2mpd

LOVED_DIR=/mnt/music8/_fav/_$(date +%Y)

mkdir -p ${LOVED_DIR}

pimpd2 --love
mpd_cp_native ${LOVED_DIR}

yes \
  | ${HOME}/dev/beets/beet modify loved=1 "${XDG_MUSIC_DIR}$(mpc current --format %file% | head -1)"


notify-send "$(mpc current --format "%title% by %artist%"| head -1)" -u critical -i /usr/share/icons/Adwaita/32x32/emotes/emote-love-symbolic.symbolic.png -t 3500

perl /home/scp1/dev/ls--/ls++ --sort=time -r ${LOVED_DIR}

beet splupdate '+by plays/loved.m3u'
