#!/bin/sh
# vim:ft=sh:et:
# abstract: update lyrics db on github
cd $HOME/dev/lyrics             &&
  git add .                     &&
  git commit -m 'update lyrics' &&
  git push

cd $HOME/dev/private &&
git add . 
git commit -m 'update'
git push
