#!/usr/bin/perl
#use strict;
use Text::Markdown qw(markdown);
use File::Temp     qw(tempfile);
use utf8;
use open qw(:std :utf8);


my($fh, $file) = tempfile('markdown_previewXXXX', SUFFIX => '.html');
print $fh markdown(do { local $/; <> });
close $fh;

system( ($ENV{DISPLAY}) ? 'x-www-browser' : $ENV{BROWSER}, $file);
unlink $file;
