#!/bin/sh
# vim: ft=sh:
while true; do
  mplayer \
    -include ${HOME}/etc/mplayer/config \
    -profile sid  \
    -softvol      \
    -volume 30    \
    http://sverigesradio.se/topsy/direkt/179-hi.mp3
  sleep 0.86
done
