#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';
use File::Copy;
use File::Path          qw(make_path);

_mkdir(@ARGV);

sub _mkdir {
  for my $file(@_) {
    if(-f $file) {
      if($file =~ m|(.+)[.].+$|) { # I know, works for me for now.
        my $new_dir = $1;
        if(make_path($new_dir)) {
          if(File::Copy::move($file, $new_dir)) {
            printf("%50.50s => %s\n", $file, $new_dir);
          }
          else {
            die "ERROR: $@\n";
          }
        }
        else {
          die "WARNING: $@\n";
        }
      }
    }
  }
}
