#!/bin/zsh
# vim: ft=sh:

mkdir -p $HOME/http

for drive in /mnt/{Music_{1..7},Books}
do
  fusermount -u $drive &> /dev/null
  sshfs -s -C \
    -o workaround=all         \
    -o allow_root             \
    -o reconnect              \
    -o cache_timeout=8        \
    -o cache_timeout=8        \
    -o transform_symlinks     \
    -o follow_symlinks        \
    -o default_permissions    \
    -o hard_remove            \
    -o direct_io              \
    -o umask=0077             \
    -o uid=1000               \
    -o sync_read              \
  laleh:${drive} ${drive}
done
for drive in /mnt/Games_{1..2} /mnt/TV_{1,2,3,4} /mnt/Movies_{1,2,3,4}
do
  fusermount -u $drive &> /dev/null
  sshfs -s -C \
    -o workaround=all         \
    -o allow_root             \
    -o reconnect              \
    -o cache_timeout=8        \
    -o cache_timeout=8        \
    -o transform_symlinks     \
    -o follow_symlinks        \
    -o default_permissions    \
    -o hard_remove            \
    -o direct_io              \
    -o umask=0077             \
    -o uid=1000               \
    -o sync_read              \
  rambo:${drive} ${drive}
done

fusermount -u /mnt/n900 &> /dev/null
fusermount -u /mnt/n950 &> /dev/null
sshfs -s -C -o reconnect n900:/ /mnt/n900
sshfs -s -C -o reconnect n950:/ /mnt/n950
sshfs -s -C -o reconnect $HOME/.CD n900:MyDocs/.sounds
sshfs -s -C -o reconnect rambo:/mnt/Mvids /mnt/Mvids
sshfs -s -C -o reconnect india:/ /mnt/india
sshfs -s -C -o reconnect xfloff.se:/ /mnt/floff
