#!/usr/bin/perl
# abstract: goto now playing artist directory

use strict;
use warnings;

use open qw(:std :utf8);
use Audio::MPD;
use IPC::Cmd qw(run);

my $mpd = Audio::MPD->new;

my $path = "$ENV{XDG_MUSIC_DIR}/" . $mpd->current->file;

my ($artist_path) = $path =~ m{^(.+)/.+/.+[.].+$};

run(
  command => "urxvt -name sid -chdir '$artist_path'",
  verbose => 0,
);
