#!/usr/bin/perl
# abstract: display cover art for currently playing albu±:

use strict;
use warnings;

use open qw(:std :utf8);
use Audio::MPD;
use IPC::Cmd qw(run);

my $mpd = Audio::MPD->new;

my $path = "$ENV{XDG_MUSIC_DIR}/" . $mpd->current->file;

my ($album_path) = $path =~ m{^(.+)/.+[.].+$};

run(
  command => "/usr/bin/feh -B black -.  -r '$album_path'",
  verbose => 0,
);
