#!/bin/bash
# abstract: update coverart on httpd for playing song in mpd for use in homeassistant
# better use the idle loop but...
oldsong=$(mpc current)

# Stays on loop while the script is active
while "true"; do
  # Check if the current song is equal to the one that was playing before (oldsong)
  if [[ "$(mpc current)" != "$oldsong" ]]; then
    # If not equal, assign the new song to the variable to be checking again correctly
    oldsong=$(mpc current)

    # update coverart
    DIRNAME=$(echo /mnt/music8/+TAGGED/$(mpc --format=%file%|head -1) | perl -MFile::Basename -lnE 'say dirname($_)')
    scp "${DIRNAME}"/cover.* debbie:/var/www/html/_pix/
  fi
  sleep 10
done
