#!/usr/bin/perl
use strict;
use Audio::MPD;

my $mpd = Audio::MPD->new;

my $basedir  = '/mnt/Music_1';
my $current  = $mpd->current->file;
my $file = "$basedir/$current";

my ($basename) = $current =~ m;.+/(.+)$;;


system("scp -P 19216 '$file' scp1\@192.168.1.128:http/japh.se/pub/");
system("echo http://l.japh.se/$basename");
system("echo http://l.japh.se/$basename|xclip");
