#!/usr/bin/perl
# Example script that shows how one can use Mplayer::NowPlaying
use strict;
use Mplayer::NowPlaying qw($np_log np);

$np_log =  "$ENV{HOME}/.mplayer/mplayerd.log";

if(@ARGV) {
  printall();
}

printf("mplayer: %s - %s (%s) [%s]\n", 
  np('artist'), np('title'), np('album'), np('genre'));

sub printall {
  printf("\033[38;5;197m\033[3m MPLAYER\033[0m\033[38;5;148m is playing\033[0m:\n");
  my $artist  = np('artist');
  my $album   = np('album');
  my $title   = np('title');
  my $year    = np('year');
  my $file    = np('file');
  my $track   = np('track');
  my $genre   = np('genre');
  my $comment = np('comment');
  
  my $codec   = np('codec');
  my $format  = np('format');
  my $length  = np('length');
  my $channels= np('channels');
  my $bitrate = sprintf("%d", np('bitrate'));

  printf("\033[38;5;033m\033[1m%10s\033[0m: %s\n", 'Artist', $artist)
    unless !$artist;
  printf("\033[38;5;032m\033[1m%10s\033[0m: %s\n", 'Album',  $album)
    unless !$album;
  printf("\033[38;5;031m\033[1m%10s\033[0m: %s\n", 'Song',   $title)
    unless !$title;
  printf("\033[38;5;030m\033[1m%10s\033[0m: %s\n", 'Year',   $year)
    unless !$year;
  printf("\033[38;5;029m\033[1m%10s\033[0m: %s\n", 'File',   $file)
    unless !$file;
  printf("\033[38;5;035m\033[1m%10s\033[0m: %s\n", 'Track',  $track)
    unless !$track;
  printf("\033[38;5;036m\033[1m%10s\033[0m: %s\n", 'Genre',  $genre)
    unless !$genre;
  printf("\033[38;5;037m\033[1m%10s\033[0m: %s\n", 'Comment',$comment)
    unless !$comment;
  printf("\033[38;5;050m\033[1m%10s\033[0m: %s\n", 'Codec',  $codec)
    unless !$codec;

  printf("\033[38;5;049m\033[1m%10s\033[0m: %s\n", 'Format', $format)
    unless !$format;
  printf("\033[38;5;048m\033[1m%10s\033[0m: %s\n", 'Length', $length)
    unless !$length;
  printf("\033[38;5;047m\033[1m%10s\033[0m: %s\n", 'Channels', $channels)
    unless !$channels;

  exit 0;


}
