#!/bin/sh

# It's VERY important to flash the eMMC first, remove the battery for a moment
# and then flash the rootfs image!
# Do NOT UNDER ANY CIRCUMSTANCES USE THE -R FLAG!

# latest eMMC:
# http://tablets-dev.nokia.com/nokia_N900.php?f=RX-51_2009SE_10.2010.13-2.VANILLA_PR_EMMC_MR0_ARM.bin

# latest Maemo 5 release:
# http://tablets-dev.nokia.com/nokia_N900.php?f=RX-51_2009SE_3.2010.02-8_PR_COMBINED_MR0_ARM.bin

# XXX WARNING:
# Using this approach results in the n900 not finding any cellular networks.
# Seems we have to use the COMBINED image instead.

# Standard approach                                                          {{{
#rmmod cdc_phonet
#flasher-3.5 -F /mnt/Docs/n900/RX-51_2009SE_10.2010.13-2.VANILLA_PR_EMMC_MR0_ARM.bin  -f
#
#printf "Remove battery for a moment. Then run:\n\t%s\n" "rmmod cdc_phonet; flasher-3.5 -F /mnt/Docs/n900/RX-51_2009SE_3.2010.02-8_PR_COMBINED_MR0_ARM.bin -f"
#}}}

rmmod cdc_phonet
flasher-3.5 -F /mnt/Docs/n900/RX-51_2009SE_3.2010.02-8_PR_COMBINED_MR0_ARM.bin -f
