#!/usr/bin/perl
use strict;

my @words;
for my $list(
  '/usr/share/dict/cracklib-small',
  "$ENV{XDG_DOCUMENTS_DIR}/wordlists/big",
) {
  open(my $fh, '<', $list) or next;
  push(@words, <$fh>);
}
#open(my $fh, '<', '/usr/share/dict/cracklib-small') or die($!);
##open(my $fh, '<', '/home/scp1/doc/wordlist_swedish.txt');
##open(my $fh, '<', "$ENV{HOME}/usr/share/doc/wordlists/big") or die($!);
my @words = grep{ (length($_) > 4) && lc(chomp($_)) } @words;

my $re = shift;

for my $w( sort{ length($a) <=> length($b) } grep{ m/$re/ } @words) {
  print "$w\n";
}

