#!/usr/bin/perl
# np
use strict;
use Audio::MPD;
my $m = Audio::MPD->new;
my $c = $m->current;
my $out;
if(!$c->artist) {
  $out = sprintf("np> %s (no id3)",$c->file);
}
else {
  $out = sprintf("np> %s: %s (%s) \@ %skbps \{%s\} [%s]",
                  $c->artist, $c->title, $c->album, $m->status->bitrate,
                  $c->genre, $c->date);
              }

print $out, "\n";                
system("printf \"$out\"|xclip");
