#!/bin/sh
# vim:ft=zsh:synmaxcol=140:


beet info "$XDG_MUSIC_DIR/$(mpc --format %file%|head -1)"

#albumartist, album, 




#/home/scp1/mp3/music8/+TAGGED/A/Anna Ternheim/Anna Ternheim │2019│ A Space for Lost Time [WEB, MP3]/05 Remember This.mp3
#             album: A Space for Lost Time
#       albumartist: Anna Ternheim
#albumartist_credit: Anna Ternheim
#  albumartist_sort: Ternheim, Anna
#       albumstatus: Official
#         albumtype: album
#          arranger: 
#               art: False
#            artist: Anna Ternheim
#     artist_credit: Anna Ternheim
#       artist_sort: Ternheim, Anna
#          bitdepth: 0
#           bitrate: 258946
#               bpm: 0
#          channels: 2
#              comp: False
#           country: DE
#              date: 2019-09-20
#               day: 20
#              disc: 1
#         disctotal: 1
#            format: MP3
#             genre: Indie
#            genres: Indie
#             label: BMG
#          language: eng
#            length: 183.68
#            lyrics: In the city where we met
#Black leaves in the wintertime
#The stage is set
#There's a part to play for everyone
#I held on to my beliefs
#Every time life let me down
#Love was just a traveler passing through
#Changes are all that I really knew
#
#Just a ? remember this
#A soul stays forever young
#Someone walks into your life
#Hopefully could be the one
#?? enemies
#My mind's a million miles away
#I don't even know your name
#But it echoes on and on and on
#I don't even know your name
#But it echoes on and on and on
#
#In a city so alone
#Some grow young, some grow old
#Chased by their own shadows
#With their eyes set on the throne
#I held on to my beliefs
#Every time life let me down
#Fate's a wicked friend
#Who lives on, no matter what
#And without regret
#
#Just a ? remember this
#A soul stays forever young
#Someone walks into your life
#Hopefully could be the one
#?? enemies
#My mind's a million miles away
#I don't even know your name
#But it echoes on and on and on
#I don't even know your name
#But it echoes on and on and on
#
#Just as love finds you dim
#It goes on and on and on
#I don't even know your name
#But it echoes on and on and on
#  mb_albumartistid: 3eb72791-6322-466b-87d3-24d74901eb2d
#        mb_albumid: 0c78a9b3-d019-481f-9bf0-0bf485940584
#       mb_artistid: 3eb72791-6322-466b-87d3-24d74901eb2d
# mb_releasegroupid: be6321c2-108f-4ff6-a1aa-f8e445488ec0
# mb_releasetrackid: 8aa45938-133b-4456-b793-c43c1a254738
#        mb_trackid: c1850ded-abe4-47a9-9722-88907cfc173e
#             media: Digital Media
#             month: 9
#     original_date: 2019-09-20
#      original_day: 20
#    original_month: 9
#     original_year: 2019
#        samplerate: 44100
#             title: Remember This
#             track: 5
#        tracktotal: 10
#              year: 2019
#
