#!/usr/bin/perl
# abstract: dump info from beets and pimpd2 about now playing song in mpd
use strict;
use warnings;

use DDP;

use Music::Beets::Info qw(beet_info);
use App::Pimpd;
use App::Pimpd::Playlist::Favorite qw(already_loved);

use File::LsColor qw(ls_color);

$config{loved_database} = "$ENV{HOME}/var/pimpd2/pimpd2.db";
#p %App::Pimpd::config;


my $mpd = Audio::MPD->new;
my $file = $ENV{XDG_MUSIC_DIR} . $mpd->current->file;

my $love = already_loved($mpd->current->file); 

my $data = beet_info($file);

printf "> %s\n", ls_color($file);
$data->{loved} = 'YES' if $love;
p $data;
