#!/bin/sh
# vim: ft=sh et sw=2 fen fdm=marker fmr=#<,#>:

#<scenario
##  # pacman -S obscurepkg
##  (1/1) installing obscurepkg
##  # ^D
##  $
##  $ rehash
##  $ obscurepkg
##  zsh: command not found: obscurepkg
#>

pacman -Ql "$@" \
  | perl -lne '
    m!bin/([ -~]+)$! && print map {
      (-x "$_/$1" && ! -l "$_/$1")
        ? "\e[38;5;30m$_\e[1m/\e[m\e[38;5;208;3m$1\e[m"
        : ""
      } split /:/, $ENV{PATH}'
