#!/usr/bin/perl
use strict;
use File::Copy;

my $int_host = '192.168.1.128';
my $ext_host = 'http://p.japh.se';

my @html;
for(@ARGV) {
  -f $_ and vimpaste($_);
  my $time_str = substr(time(), -3);
  move("$_.html", "$_-$time_str.html") and push(@html, "$_-$time_str.html");
}

for(@html) {
  system("scp -P 19216 $_ $int_host:/home/scp1/http/japh.se/paste/");
  my $abs_url = "$ext_host/$_";
  print "$abs_url\n";
  system("echo $abs_url|xclip && rm -v $_");
}

sub vimpaste {
  for(@_) {
    system("vim \"$_\" -c 'set nonumber' -c TOhtml -c :w :q! -c :q!");
  }
}
