#!/usr/bin/perl
# paste
# for xeon-enouf ;p
use strict;
use File::Copy;

my @files = @ARGV or die;
my $int_host = '192.168.1.101';
my $ext_host = 'http://paste.trapd00r.se';

for(@files) {
  system("vim \"$_\" -c 'set nonumber' -c TOhtml -c :w :q! -c :q! -c :q!");
  move("$_.html", "$_-@{[time()]}.html");
}

for my $file(@files) {
  my($basedir, $basename);

  if($file =~ /(.+\/)+(.+)/) {
    $basedir  = $1;
    $basename = $2; # eq file
  }
  else {
    $basedir  = './';
    $basename = $file;
  }

  $basename .= "-@{[time()]}";

  system("scp -P 19216 \"$basedir/$basename.html\" $int_host:/home/srv/http/paste/");
  my $fullstr = "$ext_host/$basename";
  system("printf \"$fullstr.html\n\" && printf \"$fullstr.html\"|xclip && rm -v \"$basedir/$basename.html\"");
}

