#!/usr/bin/perl
use strict;

my $pod = shift // '/home/scp1/devel/Mplayer::NowPlaying/README.pod';

parse($pod);

sub parse {
  my $file = shift;
  open(my $fh, '<', $file) or die($!);

  while(<$fh>) {
    next if(/^=pod/);
    s/=head1 (.+)/\033[1m\033[38;5;214m  $1\033[0m/;
    s/=head2 (.+)/\033[3m\033[38;5;208m  $1\033[0m/;
    s/I<(.+)> /\033[3m\033[38;5;196m$1 \033[0m/;
    s/B<(.+)> /\033[38;5;106m$1 \033[0m/;
    s/^\s+(.+)/\033[38;5;107m$1\033[0m/;
    s/<(http:.+)>/\033[38;5;32m$1\033[0m/;
    exit(1) if(/^=cut/);
    print;
  }
}
