#!/bin/sh

/bin/rm -vr "$@" \
  | sort \
  | perl -MFile::LsColor=ls_color_internal -lne '
    s/removed `(.+)(.$)/"removed \e[38;5;240m`\e[m" . ls_color_internal($1) . "\e[38;5;240m$2\e[m"/e;
    print'
