#!/usr/bin/ruby

while 1
  print "\e[38;5;202;1m>\e[m "
  begin
    str    = gets
    error  = nil

    result = eval( str )
    rescue SyntaxError, NameError => error
      puts "\e[1mDoes no compute\e[m: \e[38;5;160m" + error + "\e[m"
    end

  if !error
    print "\e[38;5;34m", result, "\e[m\n"
  end
end
