#!/bin/sh
# abstract: undefine keys for switching workspaces
# to disable/change metakey + F-keys prior to launching a game from steam and restoring the settings when the game finishes:
# sdorfehs-undefine-escapekey;sdorfehs-undefinekey-tops; %command%; sdorfehs-define-escapekey;sdorfehs-definekey-tops
sdorfehs -c 'undefinekey top s-1'
sdorfehs -c 'undefinekey top s-2'
sdorfehs -c 'undefinekey top s-3'
sdorfehs -c 'undefinekey top s-4'
sdorfehs -c 'undefinekey top s-5'
sdorfehs -c 'undefinekey top s-6'
sdorfehs -c 'undefinekey top s-7'
sdorfehs -c 'undefinekey top s-8'
sdorfehs -c 'undefinekey top s-9'
sdorfehs -c 'undefinekey top s-0'
sdorfehs -c 'undefinekey top s-q'
sdorfehs -c 'undefinekey top s-w'
sdorfehs -c 'undefinekey top s-e'

