#!/usr/bin/perl
# vim:ft=perl:
# abstract: abuse sticky bits etc to mark a movie or show as seen
use strict;
use warnings FATAL => 'all';

if(!@ARGV) {
  use Cwd ();
  push @ARGV, Cwd::abs_path
}

for my $f(@ARGV) {
  if(-f $f) {
    chmod(02740, $f) or warn "chmod: $!\n";
  }
  elsif(-d $f) {
    chmod(01700, $f) or warn "chmod: $!\n";
  }
  else {
    warn "E: $_ is neither a file or a directory\n";
  }
}
