#!/bin/sh
if [ $@ ]; then
  DNAME="$1"
  ssh -p 19216 scp1@192.168.1.100 "mkdir -p http/japh.se/scrots/$DNAME"
  echo "http/i.japh.se/$DNAME"
else
  DNAME="scrots"
fi


shot() {
  FNAME=$(date +%s.png)
  scrot $FNAME;
  scp -P 19216 $FNAME scp1@192.168.1.100:http/japh.se/scrots/$DNAME &&
    rm $FNAME &&
    echo $FNAME &&
    echo http://i.japh.se/$DNAME/$FNAME|xclip
}

shot

