#!/bin/sh
# abstract: take screenshot and upload to httpd

shot() {
  FNAME=$(date +%s.png)
  /usr/bin/scrot $@ $FNAME;
  scp $FNAME pi@pi:httpd/scrots/$DNAME &&
    rm $FNAME &&
    echo http://i.japh.se/$DNAME/$FNAME|xclip
}

shot $@
