#!/bin/sh
if [ $@ ]; then
  DNAME="scrots/$1"
  ssh -p 19216 scp1@192.168.1.102 "mkdir -p http/psy/$DNAME"
  echo "http/psy/$DNAME"
else
  DNAME="scrots"
  echo "http/psy/$DNAME"
fi


shot() {
  FNAME=$(date +%s.png)
  scrot $FNAME;
  scp -P 19216 $FNAME scp1@192.168.1.102:http/psy/$DNAME &&
    rm $FNAME &&
    echo $FNAME &&
    echo http://psy.trapd00r.se/$DNAME/$FNAME|xclip
}

shot

