#!/usr/bin/perl
# <3 dunz0r
use strict;
use LWP::Simple;


sub fav {
  my %top100 = ();
  for(split(/\n/, get("http://www.c64.org/HVSC/DOCUMENTS/Creators.txt"))) {
    m;\s*([0-9]+)+.+(/MUSICIANS/.+\.sid);;
    $top100{$1} = $2;
  }
  return(\%top100);
}

sub play {
  my $sids = fav();
  for my $n(sort {$b <=> $a} (keys(%$sids))) {
    printf("\e[1m%3d\e[0m %s\n", $n, $sids->{$n})
      unless($n == 0);

  }
  chomp(my $choice = <STDIN>);
  # yeah, I know
  system('wget', "http://www.c64.org/HVSC/$sids->{$choice}", '-O', "$$.sid");;
  system('sidplay2', "$$.sid");
  unlink("$$.sid");

}

play();

