#!/usr/bin/perl
use strict;

my $alias = "$ENV{HOME}/etc/zsh/02-alias.zsh";

open(my $fh, '<', $alias) or die($!);

my %aliases;

while(<$fh>) {
  next if /^#/;
  if(m/^\s*alias\s+(\w+)=(?:'|")(.+)(?:'|")/) {
    $aliases{$1} = $2;
  }
}

for my $k(sort{ $aliases{$b} cmp $aliases{$a} } (keys(%aliases))) {
  print "alias $k='$aliases{$k}'\n";
}
