#!/usr/bin/perl
# vim:ft=perl:
# abstract: dump all term attributes and visualize various term settings
use strict;
use warnings FATAL => 'all';

use File::LsColor ':all';
use Term::ExtendedColor qw(fg);
use Term::hr {
  fg     => 137,
  char   => '-',
  bold   => 1,
  italic => 1,
  width  => 40,
  crlf   => 1,
};

my $attr = {
  normal        => 0,
  bold          => 1,
  faint         => 2,
  italic        => 3,
  bolditalic    => '1;3',
  underline     => 4,
  undercurl     => '4:2',
  blink         => 5,
  blink_ms      => 6,
  reverse       => 7,
  conceal       => 8,
  lookup        => 9,
  double_underline => 21,
  overline      => 53,
  strikethrough => 9,
};

select STDOUT;

my $hr = hr();
print $hr;

for my $t( sort { $attr->{$a} cmp $attr->{$b} } keys(%{ $attr })) {
  $t =~ /^blink/ and printf("%s\t\t\t    \e[48;5;196;38;5;233;1;3mSKIPPING: SHOULD NEVER HAVE BEEN IMPLEMENTED\e[m\n", sprintf("%-10s", $t)), next;

  if($t eq 'underline') {
    printf("\e[$attr->{$t}m$t\e[m\n%s\n", 'https://nounderlineonlinks.se');
  }
  elsif($t eq 'undercurl') {
    printf("\e[4:3mundercurl\e[m\n");
    printf("\e[4;58:5:197;4:3mundercurl, colored\e[m\n");
  }
  else {
    printf("\e[$attr->{$t}m$t\e[m\n");
  }
}

print "stdout\n";
select STDERR;
print "stderr\n";
select STDOUT;
print $hr;

for my $unicode(qw(🌎)) {
  printf "\033[38;5;225m%s\033[m\033[38;5;39m%s\033[m\n",$unicode, $unicode;
}
print "\n";

printf "%s\n",   fg(10, '$File::LsColor::COLORIZE_PATH') . ' = ' . fg(33, 1);
printf "→ %s\n",   ls_color('/usr/share/perl5/core_perl/Symbol.pm');
printf "→ %s\n\n", ls_color('/a/path/and/file/without/extension/README');
printf "%s\n",   fg(10, '$File::LsColor::COLORIZE_PATH') . ' = ' . fg(33, 0);
$File::LsColor::COLORIZE_PATH = 0;
printf "→ %s\n",   ls_color('/usr/share/perl5/core_perl/Symbol.pm');
printf "→ %s\n",   ls_color('/a/path/and/file/without/extension/README');
print $hr;
