#!/usr/bin/perl
# vim:ft=perl:
# abstract: dump all term attributes and visualize various term settings
use strict;
use warnings FATAL => 'all';

use File::LsColor ':all';
use Term::ExtendedColor qw(fg);

my $attr = {
  normal        => 0,
  bold          => 1,
  faint         => 2,
  italic        => 3,
  bolditalic    => '1;3',
  underline     => 4,
  blink         => 5,
  blink_ms      => 6,
  reverse       => 7,
  conceal       => 8,
  lookup        => 9,
};

for my $t( sort { $attr->{$a} cmp $attr->{$b} } keys(%{ $attr })) {
  $t =~ /^blink/ and printf("%s\e[48;5;196;38;5;233;1;3mSKIPPING: SHOULD NEVER HAVE BEEN IMPLEMENTED\e[m\n", sprintf("%-10s", $t)), next;

# visually show if the colorUL property of urxvt is being abused for
# underlining URLs.
# https://www.japh.se/2019/01/23/color-urls-in-urxvt-without-abusing-underline-property.html

  if($t eq 'underline') {
    printf("\e[$attr->{$t}m$t\e[m <=> %s\n", 'https://www.japh.se');
  }
  else {
    printf("\e[$attr->{$t}m$t\e[m\n");
  }
}

# in case we're abusing LD_PRELOAD
# https://github.com/trapd00r/stderred
print "\nstdout\n";
select STDERR;
print "stderr\n\n";
select STDOUT;


printf "%s\n",   fg(10, '$File::LsColor::COLORIZE_PATH') . ' = ' . fg(33, 1);
printf "%s\n",   ls_color('/usr/share/perl5/core_perl/Symbol.pm');
printf "%s\n\n", ls_color('/a/path/and/file/without/extension/README');
printf "%s\n",   fg(10, '$File::LsColor::COLORIZE_PATH') . ' = ' . fg(33, 0);
printf "%s\n",   ls_color('/usr/share/perl5/core_perl/Symbol.pm');
printf "%s\n",   ls_color('/a/path/and/file/without/extension/README');
