#!/usr/bin/perl

my $dir = shift;;

if( (!-d $dir) && (-f $dir) ) {
  flac_it( $dir );
}
else {
  $dir = '.';
  print "Searching for *.{mp4,flv,webm,avi}\n";
  flac_it( (glob("$dir/*.mp4"), glob("$dir/*.flv"), glob("$dir/*.webm")) );
}

sub flac_it {
  my @files = @_;
  die("No files!\n") if !@files;

  for my $original(@files) {
    my $file_name = $original;

    my $i = 0;
    my @chars = split(//, $file_name);
    for my $c(@chars) {
      if($chars[$i] =~ m/[A-ZÅÄÖ]/) {
        $chars[$i] = "_$chars[$i]" unless $i == 2;
      }
      $i++;
    }
    $file_name = join('', @chars);

    $file_name =~ s/[.](?:mp4|flv|webm)$//i;
    $file_name .= '.flac';
    $file_name =~ s/\s+//g;

    if(-f $filename) {
      warn "\e[33;1mexists\e[m: $filename\n";
      next;
    }

    print "Original: $original\nNew: $file_name\n";
    system('ffmpeg', '-i', $original, $file_name);
  }
}
