#!/usr/bin/perl
# setopt no_hist_save_no_dups
use strict;

$0 =~ s;^.*/(\w+)$;$1;;

my $history = shift // "$ENV{XDG_DATA_HOME}/zsh/history";
my $count   = shift // 25;

open(my $fh, '<', $history) or print STDERR "$!" and exit(1);
chomp(my @records = <$fh>);
close($fh);

my %commands = ();

for(@records) {
  s/^:\s+[0-9]+:[0-9]+;//;
  next if $_ eq $0;
  $commands{$_}++;
}

for(sort { $commands{$b} <=> $commands{$a} } keys(%commands)) {
  if($count == 0) {
    exit(0);
  }
  printf("% 5d => %s\n", $commands{$_}, $_);
  $count--;
}
