#!/usr/bin/perl

use REST::Client;
use JSON;
use HTML::Entities qw(decode_entities);
use Getopt::Long;
use strict;

my $base     = 'https://www.googleapis.com/language/translate/v2?';
my $key      = 'key=AIzaSyACJybEm6lyelnYHZzXfydtk-V6-Uz48bQ&';
my $from     = 'sv';
my $to       = 'en';
my $query    = 'q=';

my %lang = (
  en  => 'English',
  sv  => 'Swedish',
);

GetOptions(
  'from:s'  => \$from,
  'to:s'    => \$to,
);

printf("%s -> %s\n", 
  (exists($lang{$from})) ? $lang{$from} : $from,
  (exists($lang{$to}))   ? $lang{$to}   : $to,
);

$from .= '&';
$to = "target=$to&";

my $full_url = join('', ($base, $key, $from, $to, $query));

while (1) {
  print "From: ";
  chomp ( $_ = <STDIN>);

  my $client = REST::Client->new();
  $client->GET( $full_url . $_ );
  my $response = $client->responseContent();

  my $json_text = from_json( $response );

  for my $t(@{$json_text->{data}->{translations}}) {
    my %ep;
    $ep{translatedText} = "  To: $t->{translatedText}";
    while (my($key, $value) = each (%ep)) {
      print decode_entities($value);
    }
  }
  print "\n";
}
