#!/usr/bin/perl
use strict;


my @wanted = map { qr/(?i)$_/ } qw(
  the[.]simpsons
  uppdrag[.]granskning
  talang[.]20[0-9]{2}
  solsidan
  sofias[.]anglar
  house[.]
  pluras?[.]
  SVT.dox
  lyxfallan
  fringe[.]
  californication
  landskampen
  112[.]p(?:a[.]|oliser)
);

while(<>) {
  chomp;
  for my $w(@wanted) {
    if($_ =~ m/$w/) {
      print "$_\n";
    }
  }
}
