#!/usr/bin/perl
use strict;
use vars qw($VERSION);
my $APP  = '';
$VERSION = '0.001';
use utf8;
use open qw(:utf8 :std);

use charnames qw(:full);

for my $ord( (0x2190 .. 0x21ff), (0x2900 .. 0x297f), (0x2b00 .. 0x2b59) ) {
  printf("%6d, %6x: %s %s\n", $ord, $ord, chr($ord), charnames::viacode($ord));
}
