#!/usr/bin/perl
# vim:ft=perl:
# abstract: unicode music
use vars qw($VERSION);
use strict;
use charnames qw(:full);

use open qw(:std :utf8);

for my $ord(0x1d100 .. 0x1d1ff,0x1b61 .. 0x1b7c,0xd0000 .. 0x1d0ff,0x266e,0x266f) {
  printf("%6d, %6x: %s %s\n", $ord, $ord, chr($ord), charnames::viacode($ord));
}
