#!/usr/bin/perl
# vim: ft=perl smc&:
# abstract: uppercase first

use strict;

my $line = shift;
chomp($line = <>) unless defined $line;

my @words = ($line =~ m/(\S+)/g);

printf "%s\n", $_ for map { ucfirst(lc($_)) } @words;

