#!/bin/sh
# This will query the terminal for the current font in use. It will only work
# in xterm compatible terminals.
# urxvt note: you *must* have enabled frills *and* you must set the insecure
# resource. xterm is 'insecure' by default.

printf "\e]710;?\a"; xxd
printf "\e]711;?\a"; xxd
printf "\e]712;?\a"; xxd

printf "\e]50;?\a"; xxd
