#!/bin/bash

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

# Allow users to override command-line options
if [[ -f $XDG_CONFIG_HOME/chrome-flags.conf ]]; then
   CHROME_USER_FLAGS="$(cat $XDG_CONFIG_HOME/chrome-flags.conf)"
fi

# smaller ui elements
#  --high-dpi-support=0 --force-device-scale-factor=0.82
# Launch
exec /opt/google/chrome/google-chrome $CHROME_USER_FLAGS \
	--simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
  --high-dpi-support=0 \
  --force-device-scale-factor=0.82 "$@"
