#!/usr/bin/perl
use strict;
use Parallel::ForkManager;

my @u = qw(

  http://www.youtube.com/watch?v=_MKgk8n4DZA
  http://www.youtube.com/watch?v=7JBamVtPtYM
  http://www.youtube.com/watch?v=zmWXajFn3Qo
  http://www.youtube.com/watch?v=geGW4xguI8o
  http://www.youtube.com/watch?v=STBELS4_7WQ
  http://www.youtube.com/watch?v=JRLl2yVrJzE


);

my $pm = Parallel::ForkManager->new( scalar(@u) );

for my $url(@u) {
  $pm->start and next;
  chdir('/mnt/Mvids_2') or die;
  exec('clive', $url);
  $pm->finish;
}
$pm->wait_all_children;





=pod

=head1 NAME

=head1 SYNOPSIS

=head1 DESCRIPTION

=head1 OPTIONS

=head1 AUTHOR

  Magnus Woldrich
  CPAN ID: WOLDRICH
  magnus@trapd00r.se
  http://japh.se

=head1 REPORTING BUGS

Report bugs on rt.cpan.org or to magnus@trapd00r.se

=head1 COPYRIGHT

Copyright (C) 2011 Magnus Woldrich. All right reserved.
This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;


# vim: set ts=2 et sw=2:

