#!/bin/bash

### Script for downloading albums from Youtube Music ##########
### Usage: ./yt-music-album-download.sh <youtube music url> ###

# - Converts to MP3 from the best quality audio feed
# - Adds track number, album, artist, title, and release year into id3 tags
# - Adds album art embedded thumbnails
# - Saves album art as cover.jpg in the album directory

echo "Retrieving album information..."
# Downloading the json data of the first track only
jsondata=$(yt-dlp -j --playlist-items 1 "$1")

# Grabbing the "release_year" and "release_date" and comparing which is lowest integer.
jq_release_year_1=$(echo "$jsondata" | jq -r '.release_year')
jq_release_date=$(echo "$jsondata" | jq -r '.release_date')
if [ "$jq_release_date" != "null" ]; then
    jq_release_year_2=${jq_release_date::-4}
    year=$((jq_release_year_1<jq_release_year_2?jq_release_year_1:jq_release_year_2))
else
    year=$jq_release_year_1
fi

# Grabbing the artist then removing any superfluous information after the first comma.
jq_artist=$(echo "$jsondata" | jq -r '.artist')
artist=${jq_artist%%,*}

# Grab album title (needed for cover path)
jq_album=$(echo "$jsondata" | jq -r '.album')

echo "Album information retrieved..."
album_dir="${artist} - ${jq_album}"

# Download album cover art separately and save it as cover.jpg
cover_url=$(echo "$jsondata" | jq -r '.thumbnails[-1].url')
mkdir -p "$album_dir"
wget -q "$cover_url" -O "$album_dir/cover.jpg"

# Pass to yt-dlp and begin downloading all the music
yt-dlp --ignore-errors \
    --format "(bestaudio[acodec^=opus]/bestaudio)/best" \
    --extract-audio \
    --audio-format mp3 \
    --audio-quality 0 \
    --parse-metadata "playlist_index:%(track_number)s" \
    --parse-metadata ":(?P<webpage_url>)" \
    --parse-metadata ":(?P<synopsis>)" \
    --parse-metadata ":(?P<description>)" \
    --add-metadata \
    --postprocessor-args "-metadata date='${year}' -metadata artist=\"${artist}\" -metadata album_artist=\"${artist}\"" \
    --embed-thumbnail \
    --ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" \
    -o "$album_dir/%(playlist_index)s - %(title)s.%(ext)s" "$1"

