#!/bin/sh
yt-dlp \
  --ignore-errors              \
  --format bestaudio           \
  --extract-audio              \
  --audio-format mp3           \
  --audio-quality 192K         \
  --output "%(title)s.%(ext)s" \
  --add-metadata               \
  --yes-playlist "$@"


